# Uncomment the next line to define a global platform for your project
platform :tvos, '9.0'

target 'Example-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for Example-tvOS
  pod 'AppAuth', :path => '../../'
end
